### ISSUE TITLE
v1.0 Task List

### ISSUE THREAD

**Issue by ericnewton76** [cpcontrib/accessapi-clients-nodejs#1]
- [x] improve handling of accessapi-config.json, allow for it to exist in parent paths
- [ ] separate auth to return a connection to accessapi using options, from a SOLID design philosophy makes more sense then a global config object driving all access.  Might enable better nodejs server interactions to be possible.
- [ ] review output of commands to support quiet/verbose for using this in higher level scripts and piping inputs and outputs
